### PR TITLE
fix: Fixed issue when only downloading prebuilts and proxy hosts

### LINKED ISSUE #233: Unable to download prebuilts on v10 of native-metrics
We're trying to move to Node.js 20(.6.0) since it will be LTS in a month and we have currently have to add Python and node-gyp packages to our x64 and arm64 Docker images to build this module (and `inspect-fn`).

Would it be possible to add pre-built binaries here?

### PR DESCRIPTION
**Pull request by bizob2828**
with Node 20 and using a proxy server.

## Proposed Release Notes
 * Fixed issue where it could not download prebuilts.
 * Fixed issue in Node 20 with using a proxy server to download prebuilts.

## Links
Closes #233 

## Details
This was a fun one.  Our integration tests were masking two different issues.  We create a local server to serve a local built copy from /var/tmp.  The first issue occurred during a refactor in #228, specifically this [line](https://github.com/newrelic/node-native-metrics/pull/228/files#diff-0c53b29649c837de242ad4d6b8664ad47e7a311bdfdeb217c845778395484837L59).  The 2nd issue with the proxy server was just masked in Node 20 because of the same root cause of not deleting the `build/Release` folder after every test.

### CODE REVIEW

File: lib/pre-build.js [hunk 1]
```diff
@@ -113,10 +103,10 @@ function setupRequest(url, fileName) {
 preBuild.download = async function download(target) {
   const fileName = getPackageFileName(target)
   const url = DOWNLOAD_HOST + REMOTE_PATH + fileName
-  const { client, options } = setupRequest(url, fileName)
+  const { client, options } = setupRequest()
 
   return new Promise((resolve, reject) => {
-    client.get(options, function handleResponse(res) {
+    client.get(url, options, function handleResponse(res) {
```
Comment (bizob2828) [inline lib/pre-build.js:109]: this is to appease the Node 20 gods. It seems like making an agent in options is ok in pre 20 but not in 20 so just split out url and http(s) options

File: lib/pre-build.js [hunk 2]
```diff
@@ -150,9 +140,10 @@ preBuild.download = async function download(target) {
 }
 
 preBuild.saveDownload = async function saveDownload(target, data) {
-  await preBuild.makePath(BUILD_PATH)
+  await preBuild.makePath()
 
   const filePath = path.join(BUILD_PATH, getBinFileName(target))
+  console.log('saving path', filePath)
```
Comment (mrickard) [inline lib/pre-build.js:146]: Do we want to allow the console.log here?

File: lib/pre-build.js [hunk 3]
```diff
@@ -46,21 +45,18 @@ preBuild.load = function load(target) {
...
+    await fs.access(BUILD_PATH, accessRights)
   } catch (err) {
     if (err?.code !== 'ENOENT') {
       // It exists but we don't have read+write access! This is a problem.
-      throw new Error(`Do not have access to '${pathToMake}': ${err}`)
+      throw new Error(`Do not have access to '${BUILD_PATH}': ${err}`)
     }
 
-    await fs.mkdir(pathToMake, { recursive: true })
+    await fs.mkdir(BUILD_PATH, { recursive: true })
```
Comment (bizob2828) [inline lib/pre-build.js:59]: so this was making a path of `<home>/node-native-metrics/<home>/node-native-metrics/build/Release` and it tries to save in `<home>/node-native-metircs/build/Release`. since that path did not exist it failed. So by removing `/build/Release` from the download server the path never exists as before it existed even before this function was called

**Review by mrickard — APPROVED** [review]
